<?php

namespace Tests;

use App\Models\Tenant;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use RefreshDatabase;

    public $tenant_uuid = '0eabf35d-a2a3-4c9a-b1a8-9691373902f3';
    public $tenant_db = 'tenant_1';

    public $url;

    public Tenant $tenant;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call("migrate --path=database/migrations/landlord --database=landlord");
        $this->withHeaders([
            'tenant-uuid' => $this->tenant_uuid,
            'Accept' => 'application/json',
            'user' => 2
        ]);
        $this->createTenant();
    }

    protected function createTenant()
    {
        $this->tenant = Tenant::firstOrCreate([
            'id' => 1,
            'uuid' => $this->tenant_uuid,
            'database' => $this->tenant_db
        ]);
    }
}
