services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        restart: unless-stopped
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/ifb_business
        depends_on:
            - db
            - php
        networks:
            - ifb

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/ifb_business
        user: "1000:1000"
        networks:
            - ifb

    db:
        image: mariadb
        ports:
            - "3300:3306"
        restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: YES
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - ifb

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8800:80
        depends_on:
            - db
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 640M
        networks:
            - ifb

    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - .:/var/www/ifb_business
        user: "1000:1000"
        networks:
            - ifb

    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - .:/var/www/ifb_business
        user: "1000:1000"
        networks:
            - ifb
        entrypoint: ["php", "/var/www/ifb_business/artisan"]

volumes:
    db_data:
    elastic_data:

networks:
    ifb:
        driver: bridge
        external: true
