<?php

namespace app\models;

use app\helpers\NotificationHelper;
use Yii;

/**
 * This is the model class for table "{{%task_w_performer_link}}".
 *
 * @property int $id
 * @property int $performer_id
 * @property int $task_id
 * @property string|null $comments Любые комментарии
 * @property int $is_deleted
 * @property string|null $created
 * @property int|null $creator_id
 * @property string|null $modified
 * @property int|null $modifier_id
 *
 * @property User $creator
 * @property User $modifier
 * @property User $performer
 * @property Task $task
 */
class TaskWPerformerLink extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%task_w_performer_link}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['performer_id'], 'required'],
            [['task_id'], 'required', 'except' => 'insert'],
            [['id', 'performer_id', 'task_id', 'is_deleted', 'creator_id', 'modifier_id'], 'integer'],
            [['comments'], 'string'],
            [['created', 'modified'], 'safe'],
            [['performer_id', 'task_id'], 'unique', 'targetAttribute' => ['performer_id', 'task_id']],
            [['creator_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['creator_id' => 'id']],
            [['modifier_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['modifier_id' => 'id']],
            [['performer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['performer_id' => 'id']],
            [['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::class, 'targetAttribute' => ['task_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'performer_id' => Yii::t('app', 'Исполнитель'),
            'task_id' => Yii::t('app', 'Задача'),
            'comments' => Yii::t('app', 'Комментарии'),
            'is_deleted' => Yii::t('app', 'Is Deleted'),
            'created' => Yii::t('app', 'Created'),
            'creator_id' => Yii::t('app', 'Creator ID'),
            'modified' => Yii::t('app', 'Modified'),
            'modifier_id' => Yii::t('app', 'Modifier ID'),
        ];
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        $model = $this->findOne(['id' => $this->id]);
        if (empty($model)) {
            return parent::save($runValidation, $attributeNames);
        } else {
            return parent::update($runValidation, $attributeNames);
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(key_exists('performer_id', $changedAttributes) && $this->performer) {
            NotificationHelper::notifyNewTask($this->task, $this->performer);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[Creator]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(User::class, ['id' => 'creator_id'])->inverseOf('taskWPerformerLinks');
    }

    /**
     * Gets query for [[Modifier]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getModifier()
    {
        return $this->hasOne(User::class, ['id' => 'modifier_id'])->inverseOf('taskWPerformerLinks0');
    }

    /**
     * Gets query for [[Performer]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPerformer()
    {
        return $this->hasOne(User::class, ['id' => 'performer_id'])->inverseOf('taskWPerformerLinks1');
    }

    /**
     * Gets query for [[Task]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTask()
    {
        return $this->hasOne(Task::class, ['id' => 'task_id'])->inverseOf('taskWPerformerLinks');
    }
}
